---
title: "Markdown_Instructions"
author: "François Birgand"
date: "09/10/2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## What is the Markdown language?

Markdown is a simple formatting syntax with the goal of enabling people "to write using an easy-to-read, easy-to-write plain text format, and optionally convert it to structurally valid XHTML (or HTML)".  OK, so imagine that this is a writing language that is very close to plain text, where the most useful alteration of text (headings, bold, italic, web references, etc.) are simpler than the html codes. I encourage you to read the [wikipedia definition](https://en.wikipedia.org/wiki/Markdown) of Markdown to have more details of why and how it came about.

## The 'R twist' of Mardown: R Markdown
Now the beauty of Markdown is that some very smart people have thought that one could in fact embedded R codes, within the text, such that in the end, a document could contain all the text and code to create figures.  Other just as smart people have thought that one could use all the beauty of the [LaTeX](https://en.wikipedia.org/wiki/LaTeX) power, particularly for editing equations. They have also added the possibility to add citations, bibliography. All this to say that they have added all the features that students/researchers need and have dreamt about for a while! 

So the 'R twist' to Markdown is called 'R Markdown'. One of the hidden beauties is that R Mardown uses [Pandoc](https://pandoc.org/MANUAL.html), which is a universal document converter. The result is that you and I will now write in R Markdown and will have the possibility of publishing what we have written in many output formats, which include among many others HTML, pdf, and word. This is one of the major advantages compared to LaTeX, which can only produce pdf documents.

## R Markdown in R Studio
I have had very low opinion of R studio until very recently because I never liked the text editor, I always thougtht (still do in fact...!) that on a normal screen, things were just too cramped. *But*, I must say that I have come to change my mind, principally thanks to the possibilities that R Markdown offers, and because R Mardown is hosted in R studio.  

The goal of this document is thus to introduce you to R Markdown and the things you need to get to know quickly.
for authoring HTML, PDF, MS Word documents, but also many other interesting outputs. All the details on using R Markdown can be found at <http://rmarkdown.rstudio.com>.  I encourage you to browse the [gallery](http://rmarkdown.rstudio.com/gallery.html) and then spend time to get familiarized on what can be done with it on the [step by step tutorial](http://rmarkdown.rstudio.com/lesson-1.html).

